### ISSUE TITLE
GUI isnt displayed

### ISSUE THREAD

**Issue by sarash85** [collinsowusu/PyGEE-SWToolbox#1]
I can't get the GUI of the toolbox. here is what I get after running the second cell of the notebook:
<PyGEE_SWToolbox.Toolbox at 0x1c0e94b45b0>

**Comment by collinsowusu** [comment]
The cell displaying this "<PyGEE_SWToolbox.Toolbox at 0x1c0e94b45b0>" means the instance of the toolbox is running so I don't know why the GUI is not showing up. 

What web browser are you using to run your jupyter notebook?
