### ISSUE TITLE
No Landsat in dataset

### ISSUE THREAD

**Issue by MinhVu25** [collinsowusu/PyGEE-SWToolbox#2]
Hello @collinsowusu . I set up PyGEE_SW follow the instruction but when I run the toolbox on Jupyter, the dataset only contains Landsat-Collection 1, Landsat-Collection 2, Sentinel 1, Sentinel 2 and USDA NAIP. This is not showing the same as in the manual book where I see Landsat 8 at the Dataset section. Furthermore, I tried to collect some images with Landsat-Collection 1 and Landsat-Collection 2 but no image was collected, and it just showed processing status. On the other hand, this function is working well with Sentinel 1 and 2. How can I solve this? Thank you! 
![Screenshot 2022-10-17 150955](https://user-images.githubusercontent.com/115979594/196124212-986d9666-8edb-455d-bc30-8b0a1f1915e2.png)

**Comment by collinsowusu** [comment]
Hello, @MinhVu25. I designed the toolbox to retrieve all images from Landsat 4 to Landsat 8 missions if you select Landsat-Collection 1 and Landsat 4 to Landsat 9 if you select collection 2. Landsat Collection 1 has been deprecated. All data acquired after December 31, 2021 is only available in Collection 2. I will be removing Collection 1 from the toolbox in the future.

The dataset is sorted in a chronological manner  (based on the date/time of the image). So if you specify your date, the script will provide a dataset from that period by looking at the most recent Landsat mission before going to previous missions. For example, if you select a date in 2022, the script will sample Landsat 9 data first before it looks for Landsat 8.

If you don't get any images, then you have to check the date span for your analysis and the cloud threshold. There may be no available image for the specified dates and meeting the cloud threshold. Don't forget that Landsat-Collection 1 has no image after December 2021 so I encourage you to use Landsat-Collection 2.
