### ISSUE TITLE
Requirements.txt not correct

### ISSUE THREAD

**Issue by patrontheo** [collinsowusu/PyGEE-SWToolbox#3]
Hello, 
After installing your toolbox, the command `Toolbox()` wont work and will throw the error:
`AttributeError: type object 'DOMWidget' has no attribute '_ipython_display_'`
This can be solved by adapting the `requirements.txt` to:
```
earthengine_api>=0.1.304
eemont
geemap
geetools
ipyfilechooser
matplotlib
ipywidgets==7.7.2
pandas
hydrafloods
plotly==5.10.0
scikit-learn
```
I don't know if `plotly` or `ipywidgets` was responsible for the error so I downgraded both.

**Comment by collinsowusu** [comment]
Hello @patrontheo

Thanks for bringing this up and providing a solution. 
The problem is due to the recent updates to ipywidgets. It has nothing to do with Plotly
